import { Granja, Puntos, SubTitulo, Titulo, Boton, Comentarios, Lineup } from "../../Styled/Helps";

const X = () => {
    return (
        <>
            <Titulo>Privacidad</Titulo>
            <Granja>
                <Lineup>¿Necesitas ayuda? En Arte Natural nos importa mucho ayudar al cliente como el vendedor</Lineup>
                <Puntos>
                    <li>
                        <a>La transposición en plazo de directivas de la Unión Europea es un objetivo fundamental del Consejo Europeo. A este fin, la Comisión Europea somete informes periódicos al Consejo de Competitividad, a los que se les da un alto valor político por su función de medición de la eficacia y credibilidad de los Estados miembros en la puesta en práctica del mercado interior.

El cumplimiento de este objetivo resulta del todo prioritario, habida cuenta del escenario diseñado por el Tratado de Lisboa de 2007 por el que se modifican el Tratado de la Unión Europea y el Tratado constitutivo de la Comunidad Europea, para los incumplimientos de transposición en plazo, para los que la Comisión puede pedir al Tribunal de Justicia de la Unión Europea la imposición de importantes sanciones económicas de manera acelerada (artículo 260.3 del Tratado de Funcionamiento de la Unión Europea –TFUE–).

España viene cumpliendo consistentemente con los objetivos de transposición en los plazos comprometidos desde que resultan fijados los mismos. No obstante, en los últimos años, hechos como la repetición de elecciones generales en 2019, con la consiguiente disolución de las Cortes Generales, la existencia de un Gobierno en funciones durante un tiempo prolongado, así como el estadillo de la pandemia del COVID-19 en el año 2020, explican la acumulación de retrasos en la transposición de algunas directivas, que requieren de una norma con rango de ley para su incorporación al ordenamiento jurídico interno.

Tal es el caso de las Directivas cuya transposición constituye el objeto del presente real decreto-ley, dado que todas ellas se encuentran en riesgo de multa con base a lo establecido en el artículo 260.3 del TFUE. En este sentido, deben considerarse en riesgo de multa aquellas directivas para las que queda menos de 3 meses para que se cumpla su plazo límite de transposición y que necesitan, al menos, una norma con rango de ley para su transposición sin que dicha ley haya empezado su tramitación parlamentaria; así como todas aquellas directivas que tienen ya un procedimiento de infracción abierto por la Comisión Europea por haberse cumplido su plazo límite de transposición.

Como ejemplo reciente de las consecuencias económicas que pueden derivarse de estos retrasos, cabe señalar la Sentencia del TJUE de 25 de febrero de 2021 contra España (asunto C-658/19) por retraso en la transposición de la Directiva (UE) 2016/680 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativa a la protección de las personas físicas en lo que respecta al tratamiento de datos personales por parte de las autoridades competentes para fines de prevención, investigación, detección o enjuiciamiento de infracciones penales o de ejecución de sanciones penales, y a la libre circulación de dichos datos; condenando al pago de 15 millones de euros en concepto de suma a tanto alzado más 8.099.000 euros como multa coercitiva.

Ante la gravedad de las consecuencias de seguir dilatando la incorporación al ordenamiento jurídico español de tales directivas, resulta necesario acudir a la aprobación de un real decreto-ley para proceder a dicha transposición, lo que permitirá cerrar los procedimientos de infracción abiertos por la Comisión Europea.

En lo relativo a la existencia de «procedimientos de incumplimiento contra el Reino de España», debe tenerse en cuenta que pese al carácter opcional previsto en el artículo 260.3 del Tratado de Funcionamiento de la Unión Europea, en su Comunicación de 13 de diciembre de 2016, «Derecho de la UE» mejores resultados gracias a una mejor aplicación», la Comisión ha anunciado un cambio de enfoque pasando a solicitar de manera sistemática la suma a tanto alzado. La consecuencia lógica del enfoque de la suma a tanto alzado es que, en los casos en los que un Estado miembro subsane la infracción mediante la transposición de la directiva en el curso de un procedimiento de infracción, la Comisión ya no desistirá de su recurso solo por ese motivo y solicitará en cualquier caso al TJUE la imposición de la suma a tanto alzado.

Como disposición transitoria, la Comisión ha señalado que no aplicará esta nueva práctica a los procedimientos cuya carta de emplazamiento sea anterior a la publicación de dicha comunicación en el Diario Oficial de la Unión Europea que tuvo lugar el 19 de enero de 2017. En consecuencia, resulta de extraordinaria y urgente necesidad proceder a la transposición antes de que se formalice la demanda ante el Tribunal de Justicia, para evitar así un procedimiento judicial que finalizaría mediante una sentencia que declare el incumplimiento por parte del Reino de España de las obligaciones que le impone el Derecho de la Unión.

En cuanto a la utilización del real decreto-ley, el Tribunal Constitucional ha declarado que la situación de extraordinaria y urgente necesidad que exige, como presupuesto habilitante, el artículo 86.1 de la Constitución Española, puede deducirse «de una pluralidad de elementos», entre ellos, «los que quedan reflejados en la exposición de motivos de la norma» (STC 6/1983, de 4 de febrero).

Por su parte, entre la situación de extraordinaria y urgente necesidad que habilita el empleo del real decreto-ley y las medidas contenidas en él debe existir una «relación directa o de congruencia». Por tanto, para la concurrencia del presupuesto de la extraordinaria y urgente necesidad, la STC 61/2018, de 7 de junio, (FJ 4), exige, por un lado, «la presentación explícita y razonada de los motivos que han sido tenidos en cuenta por el Gobierno para su aprobación», es decir, lo que ha venido a denominarse la situación de urgencia; y, por otro, «la existencia de una necesaria conexión entre la situación de urgencia definida y la medida concreta adoptada para subvenir a ella SSTC 29/1982, de 31 de mayo, FJ 3; 182/1997, de 20 de octubre, FJ 3; y 137/2003, de 3 de julio, FJ 4)».

El real decreto-ley constituye un instrumento constitucionalmente lícito, siempre que el fin que justifica la legislación de urgencia, sea, tal como reiteradamente ha exigido nuestro Tribunal Constitucional (Sentencias 6/1983, de 4 de febrero, F. 5; 11/2002, de 17 de enero, F. 4; 137/2003, de 3 de julio, F. 3; y 189/2005, de 7 julio, F. 3), subvenir a una situación concreta, dentro de los objetivos gubernamentales, que por razones difíciles de prever precisa de una acción normativa inmediata en un plazo más breve que el requerido por la vía normal o por el procedimiento de urgencia para la tramitación parlamentaria de las leyes, máxime cuando la determinación de dicho procedimiento no depende del Gobierno.

Por otro lado, en relación con la figura del real decreto-ley como instrumento de transposición, cabe señalar que el Tribunal Constitucional en su Sentencia 1/2012, de 13 de enero, avala la concurrencia del presupuesto habilitante de la extraordinaria y urgente necesidad del artículo 86.1 de la Constitución Española cuando concurran «el patente retraso en la transposición» y la existencia de «procedimientos de incumplimiento contra el Reino de España».

Asimismo, cabe señalar que el Consejo de Estado, en su informe sobre la inserción del Derecho europeo en el ordenamiento español, de 14 de febrero de 2008, considera que, si bien no debe convertirse en mecanismo ordinario para la incorporación de las directivas, sí está justificado en atención, por ejemplo, «al plazo fijado por la norma comunitaria, a la necesidad de dar urgente respuesta a unas determinadas circunstancias o a la existencia de una declaración de incumplimiento por el Tribunal de Justicia de las Comunidades Europeas».

A mayor abundamiento, la Sentencia del Tribunal Constitucional 199/2015, de 24 de septiembre, declaró en materia de decretos-leyes transversales que «la concurrencia de la urgencia y la necesidad debe analizarse de cada precepto, porque solo de este modo podrá realizarse un examen apropiado sobre la conexión de sentido entre la situación de urgencia definida y la medida concreta adoptada para subvenir a la misma».

Asimismo, en relación con la diversidad de ámbitos y materias que el presente real decreto-ley viene a regular, se estima necesario destacar que el Tribunal Constitucional, en la Sentencia 136/2011, de 13 de septiembre, declaró que el dogma de la deseable homogeneidad de un texto legislativo no es obstáculo insalvable que impida al legislador dictar normas multisectoriales, pues tampoco existe en la Constitución Española precepto alguno, expreso o implícito, que impida que las leyes tengan un contenido heterogéneo.

De este modo, sigue diciendo en su Sentencia el Tribunal Constitucional, «por más que pueda hablarse de la existencia de una global situación de urgencia o de necesidad, vinculada a lo que este Tribunal ha denominado como «coyunturas económicas problemáticas», en los supuestos en que existe la previsión de un conjunto de medidas diversas para afrontar esa coyuntura, bien se puede exigir al Gobierno que exponga razonadamente los motivos que ha tenido en cuenta para incluir cada bloque de medidas en el decreto-ley, optando por sacarlas de la órbita de un eventual proyecto de ley específico. Por tanto (...) la valoración de la concurrencia del presupuesto habilitante en un decreto-ley transversal, pasa por verificar que la motivación relativa a la existencia de dicho presupuesto, no es una vaga motivación genérica, sino que se refiere, expresamente, a cada precepto o grupo de preceptos, con el objetivo de exteriorizar las razones que justifican la inclusión de esas medidas en un decreto-ley. Solo de este modo, quien está llamado a ejercer el control sobre el Decreto-ley puede tener presentes «las situaciones concretas y los objetivos gubernamentales que han dado lugar a la aprobación de cada uno de los Decretos-leyes enjuiciados» (SSTC 6/1983, de 4 de febrero, FJ 5; 182/1997, de 28 de octubre, FJ 3; 11/2002, de 17 de enero, FJ 4, y 137/2003, de 3 de julio, FJ 3)».

Debe señalarse también que este real decreto-ley no afecta al ordenamiento de las instituciones básicas del Estado, a los derechos, deberes y libertades de los ciudadanos regulados en el título I de la Constitución, al régimen de las Comunidades Autónomas ni al Derecho electoral general.

Por todo ello, y de acuerdo con la jurisprudencia del Tribunal Constitucional, en los sucesivos apartados de esta exposición de motivos se concretan las razones que justifican la extraordinaria y urgente necesidad de transponer las distintas directivas en cada uno de los supuestos recogidos en el presente real decreto-ley.</a>
                    </li>

                </Puntos>
            </Granja>
        </>
    );
};

export default X;